USERNAME='root'
PASSWORD='root'
SERVER='0.0.0.0'
DB='controle_financeiro'

SQLALCHEMY_DATABASE_URI=f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'

SQLALCHEMY_TRACK_MODIFICATIONS=True

SECRET_KEY='chave_secreta'